//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Merchant
    {
        public Merchant()
        {
            this.Accounts = new HashSet<Account>();
            this.TransactionDetails = new HashSet<TransactionDetail>();
        }
    
        public string MerchantID { get; set; }
        public string MerchantName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Status { get; set; }
        public string MerchantTypeID { get; set; }
        public string MerchantRegionID { get; set; }
        public string AgentID { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual MerchantRegion MerchantRegion { get; set; }
        public virtual MerchantType MerchantType { get; set; }
        public virtual Agent Agent { get; set; }
        public virtual ICollection<TransactionDetail> TransactionDetails { get; set; }
    }
}
