//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public string NotiID { get; set; }
        public string Detail { get; set; }
        public string Summary { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string SenderID { get; set; }
        public string ReceiverID { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
