//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyReport
    {
        public int ReportID { get; set; }
        public string MerchantID { get; set; }
        public string MerchantTypeID { get; set; }
        public string MerchantRegionID { get; set; }
        public Nullable<decimal> SaleAmount { get; set; }
        public Nullable<decimal> ReturnAmount { get; set; }
        public Nullable<int> SaleCount { get; set; }
        public Nullable<int> ReturnCount { get; set; }
        public Nullable<decimal> DebitCardSaleAmount { get; set; }
        public Nullable<decimal> MasterCardSaleAmount { get; set; }
        public Nullable<decimal> VisaCardSaleAmount { get; set; }
        public Nullable<decimal> DebitCardReturnAmount { get; set; }
        public Nullable<decimal> MasterCardReturnAmount { get; set; }
        public Nullable<decimal> VisaCardReturnAmount { get; set; }
        public Nullable<decimal> DebitCardSaleCount { get; set; }
        public Nullable<decimal> MasterCardSaleCount { get; set; }
        public Nullable<decimal> VisaCardSaleCount { get; set; }
        public Nullable<decimal> DebitCardReturnCount { get; set; }
        public Nullable<decimal> MasterCardReturnCount { get; set; }
        public Nullable<decimal> VisaCardReturnCount { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<int> NetCount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
