//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string Username { get; set; }
        public string Password { get; set; }
        public string UserID { get; set; }
        public string Role { get; set; }
    
        public virtual Agent Agents { get; set; }
        public virtual Merchant Merchants { get; set; }
        public virtual Master Masters { get; set; }
    }
}
