//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Merchant
    {
        public Merchant()
        {
            this.Account = new HashSet<Account>();
            this.NotificationsSend = new HashSet<Notification>();
            this.NotificationsReceive = new HashSet<Notification>();
            this.TransactionDetails = new HashSet<TransactionDetail>();
            this.DailyReports = new HashSet<DailyReport>();
            this.YearlyReports = new HashSet<YearlyReport>();
            this.MonthlyReports = new HashSet<MonthlyReport>();
        }
    
        public string MerchantID { get; set; }
        public string MerchantName { get; set; }
        public string Owner { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public string MerchantTypeID { get; set; }
        public string MerchantRegionID { get; set; }
        public string AgentID { get; set; }
    
        public virtual ICollection<Account> Account { get; set; }
        public virtual MerchantRegion MerchantRegion { get; set; }
        public virtual MerchantType MerchantType { get; set; }
        public virtual Agent Agent { get; set; }
        public virtual ICollection<Notification> NotificationsSend { get; set; }
        public virtual ICollection<Notification> NotificationsReceive { get; set; }
        public virtual ICollection<TransactionDetail> TransactionDetails { get; set; }
        public virtual ICollection<DailyReport> DailyReports { get; set; }
        public virtual ICollection<YearlyReport> YearlyReports { get; set; }
        public virtual ICollection<MonthlyReport> MonthlyReports { get; set; }
    }
}
